#!/bin/bash

while true; do
    change=$(inotifywait -e close_write,modify,moved_to,create parser src $(cat sources.list) make &)
    sleep 1
    echo Rebuilding...
    ./make
    echo Done.  Back to waiting.
done

